-- Contagem de estabelecimentos ativos no Brasil

SELECT 
	COUNT(*) 
	FROM ESTABELECIMENTOS
	WHERE ESTABELECIMENTOS.SITUACAO_CADASTRAL = '02'
;
	

-- Contagem de estabelecimentos ativos por cidade

SELECT 
	MUNICIPIO.NOME_MUNICIPIO,
	COUNT(*) 
	FROM ESTABELECIMENTOS
	LEFT JOIN MUNICIPIO ON ESTABELECIMENTOS.MUNICIPIO = MUNICIPIO.CODIGO_MUNICIPIO
	WHERE ESTABELECIMENTOS.SITUACAO_CADASTRAL = '02'
	GROUP BY MUNICIPIO.NOME_MUNICIPIO
	ORDER BY COUNT(*) DESC
;


-- Contagem de setores dos estabelecimentos ativos do Brasil

SELECT
	CASE
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 322199 THEN 'AGRICULTURA'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 500301 AND 3900500 THEN 'INDUSTRIA'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 4110700 AND 4399199 THEN 'CONSTRUCAO'
       	 	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 4511101 AND 4789099 THEN 'COMERCIO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 4911600 AND 8888887 THEN 'SERVICOS'
       		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 8888889 THEN 'SERVICOS'
       		ELSE 'NAO_INFORMADO'
	END AS "SETOR",
	COUNT(*)
	FROM ESTABELECIMENTOS
	WHERE ESTABELECIMENTOS.SITUACAO_CADASTRAL = '02' 
	GROUP BY "SETOR"
	ORDER BY COUNT(*) DESC
;


-- Contagem de matrizes e filiais ativas no brasil

SELECT
	MATRIZ_FILIAL,
	COUNT(*) 
	FROM ESTABELECIMENTOS
	WHERE MUNICIPIO = '8105' AND SITUACAO_CADASTRAL = '02'
	GROUP BY MATRIZ_FILIAL
;


-- Selecao das empresas ativas do Brasil

SELECT 	
    ESTABELECIMENTOS.CNPJ_BASICO || ESTABELECIMENTOS.CNPJ_ORDEM || ESTABELECIMENTOS.CNPJ_DV AS "CNPJ",
	EMPRESAS.RAZAO_SOCIAL AS "RAZAO_SOCIAL",
	ESTABELECIMENTOS.NOME_FANTASIA AS "NOME_FANTASIA",
	CASE
		WHEN ESTABELECIMENTOS.MATRIZ_FILIAL = '1' THEN 'MATRIZ'
		WHEN ESTABELECIMENTOS.MATRIZ_FILIAL = '2' THEN 'FILIAL'
		ELSE 'NAO INFORMADO'
	END AS "MATRIZ_FILIAL",
	CASE
		WHEN SIMPLES.OPCAO_MEI = 'S' THEN 'MEI'
		WHEN EMPRESAS.PORTE = '00' THEN 'NAO INFORMADO'
		WHEN EMPRESAS.PORTE = '01' THEN 'MICRO EMPRESA'
		WHEN EMPRESAS.PORTE = '03' THEN 'EPP'
		WHEN EMPRESAS.PORTE = '05' THEN 'DEMAIS PORTES'
	ELSE 'NAO INFORMADO'
	END AS "PORTE",
    EMPRESAS.CAPITAL_SOCIAL AS "CAPITAL_SOCIAL",
	ESTABELECIMENTOS.UF AS "ESTADO",
	MUNICIPIO.NOME_MUNICIPIO AS "MUNICIPIO",
	ESTABELECIMENTOS.BAIRRO AS "BAIRRO",
    ESTABELECIMENTOS.CEP AS "CEP",
	ESTABELECIMENTOS.TIPO_LOGRADOURO AS "LOGRADOURO",
    ESTABELECIMENTOS.NUMERO_LOGRADOURO AS "NUMERO",
	ESTABELECIMENTOS.TIPO_LOGRADOURO || ' ' || ESTABELECIMENTOS.LOGRADOURO || ', NUMERO ' || ESTABELECIMENTOS.NUMERO_LOGRADOURO AS "ENDERECO",
    ESTABELECIMENTOS.CNAE_PRINCIPAL AS "COD_CNAE",
    UPPER(CNAE.NOME_CNAE) AS "CNAE_PRINCIPAL",
	CASE
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 322199 THEN 'AGRICULTURA'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 500301 AND 3900500 THEN 'INDUSTRIA'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 4110700 AND 4399199 THEN 'CONSTRUCAO'
       	 	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 4511101 AND 4789099 THEN 'COMERCIO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 4911600 AND 8888887 THEN 'SERVICOS'
       		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 8888889 THEN 'SERVICOS'
        ELSE 'NAO_INFORMADO'
	END AS "SETOR",
	CASE
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 322199 THEN 'AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 500301 AND 990403 THEN 'INDÚSTRIAS EXTRATIVAS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 1011201 AND 3329599 THEN 'INDÚSTRIAS DE TRANSFORMAÇÃO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 3511501 AND 3530100 THEN 'ELETRICIDADE E GÁS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 3600601 AND 3900500 THEN 'ÁGUA, ESGOTO, ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 4110700 AND 4399199 THEN 'CONSTRUÇÃO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 4511101 AND 4789099 THEN 'COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 4911600 AND 5320202 THEN 'TRANSPORTE, ARMAZENAGEM E CORREIO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 5510801 AND 5620104 THEN 'ALOJAMENTO E ALIMENTAÇÃO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 5811500 AND 6399200 THEN 'INFORMAÇÃO E COMUNICAÇÃO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 6410700 AND 6630400 THEN 'ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 6810201 AND 6822600 THEN 'ATIVIDADES IMOBILIÁRIAS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 6911701 AND 7500100 THEN 'ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 7711000 AND 8299799 THEN 'ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 8411600 AND 8430200 THEN 'ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 8511200 AND 8599699 THEN 'EDUCAÇÃO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 8610101 AND 8800600 THEN 'SAÚDE HUMANA E SERVIÇOS SOCIAIS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 9001901 AND 9329899 THEN 'ARTES, CULTURA, ESPORTE E RECREAÇÃO'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) BETWEEN 9411100 AND 9609299 THEN 'OUTRAS ATIVIDADES DE SERVIÇOS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) = 9700500 THEN 'SERVIÇOS DOMÉSTICOS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) = 9900800 THEN 'ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS'
        	WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) = 8888888 THEN 'NAO INFORMADO'
        	ELSE 'NAO INFORMADO'
	END AS "CLASSE",
    ESTABELECIMENTOS.DDD1 || ESTABELECIMENTOS.TELEFONE1 AS "TELEFONE_1",
    ESTABELECIMENTOS.DDD2 || ESTABELECIMENTOS.TELEFONE2 AS "TELEFONE_2",
    ESTABELECIMENTOS.EMAIL AS "EMAIL"

	FROM ESTABELECIMENTOS
		
	LEFT JOIN EMPRESAS
	ON ESTABELECIMENTOS.CNPJ_BASICO = EMPRESAS.CNPJ_BASICO

	LEFT JOIN SIMPLES
	ON ESTABELECIMENTOS.CNPJ_BASICO = SIMPLES.CNPJ_BASICO

	LEFT JOIN CNAE
	ON ESTABELECIMENTOS.CNAE_PRINCIPAL = CNAE.CODIGO_CNAE

	LEFT JOIN MUNICIPIO
	ON ESTABELECIMENTOS.MUNICIPIO = MUNICIPIO.CODIGO_MUNICIPIO

	WHERE ESTABELECIMENTOS.SITUACAO_CADASTRAL = '02'
;

--____________________________________________________________________________________

