-- Construcao dos dados das empresas de Florianopolis com geolocalizacao

-- Criacao da tabela de geolocalizacao

CREATE TABLE GEO (
	CEP VARCHAR(8) PRIMARY KEY,
	GEO VARCHAR(200),
	ID_BAIRRO VARCHAR(5),
	BAIRRO VARCHAR(100),
	DISTRITO_PMF VARCHAR(50),
	REGIONAL_ACIF VARCHAR(50)
	)
;

\COPY GEO FROM 'D:/Geolocalizacao Florianopolis.csv' DELIMITER ';' CSV ENCODING 'WIN1252';

-- Selecao empresas ativas de Florianopolis com georefereciamento

SELECT 	
    DISTINCT ON (ESTABELECIMENTOS.CNPJ_BASICO || ESTABELECIMENTOS.CNPJ_ORDEM || ESTABELECIMENTOS.CNPJ_DV) ESTABELECIMENTOS.CNPJ_BASICO || ESTABELECIMENTOS.CNPJ_ORDEM || ESTABELECIMENTOS.CNPJ_DV AS "CNPJ",
	EMPRESAS.RAZAO_SOCIAL AS "RAZAO_SOCIAL",
	ESTABELECIMENTOS.NOME_FANTASIA AS "NOME_FANTASIA",
	CASE
		WHEN ESTABELECIMENTOS.MATRIZ_FILIAL = '1' THEN 'MATRIZ'
		WHEN ESTABELECIMENTOS.MATRIZ_FILIAL = '2' THEN 'FILIAL'
		ELSE 'NAO INFORMADO'
	END AS "MATRIZ_FILIAL",
	CASE
		WHEN SIMPLES.OPCAO_MEI = 'S' THEN 'MEI'
		WHEN EMPRESAS.PORTE = '00' THEN 'NAO INFORMADO'
		WHEN EMPRESAS.PORTE = '01' THEN 'MICRO EMPRESA'
		WHEN EMPRESAS.PORTE = '03' THEN 'EPP'
		WHEN EMPRESAS.PORTE = '05' THEN 'DEMAIS PORTES'
	ELSE 'NAO INFORMADO'
	END AS "PORTE",
    EMPRESAS.CAPITAL_SOCIAL AS "CAPITAL_SOCIAL",
	ESTABELECIMENTOS.UF AS "ESTADO",
	MUNICIPIO.NOME_MUNICIPIO AS "MUNICIPIO",
	GEO.BAIRRO AS "BAIRRO",
    ESTABELECIMENTOS.CEP AS "CEP",
	ESTABELECIMENTOS.TIPO_LOGRADOURO || ' ' || ESTABELECIMENTOS.LOGRADOURO || ', NUMERO ' || ESTABELECIMENTOS.NUMERO_LOGRADOURO AS "ENDERECO",
    ESTABELECIMENTOS.CNAE_PRINCIPAL AS "COD_CNAE",
    UPPER(CNAE.NOME_CNAE) AS "CNAE_PRINCIPAL",
	CASE
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 322199 THEN 'AGRICULTURA'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 500301 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 3900500 THEN 'INDUSTRIA'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 4110700 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 4399199 THEN 'CONSTRUCAO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 4511101 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 4789099 THEN 'COMERCIO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 4911600 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 8888887 THEN 'SERVICOS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 8888889 THEN 'SERVICOS'
		ELSE 'NAO INFORMADO'
	END AS "SETOR",
	CASE
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 322199 THEN 'AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 500301 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 990403 THEN 'INDÚSTRIAS EXTRATIVAS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 1011201 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 3329599 THEN 'INDÚSTRIAS DE TRANSFORMAÇÃO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 3511501 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 3530100 THEN 'ELETRICIDADE E GÁS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 3600601 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 3900500 THEN 'ÁGUA, ESGOTO, ATIVIDADES DE GESTÃO DE RESÍDUOS E DESCONTAMINAÇÃO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 4110700 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 4399199 THEN 'CONSTRUÇÃO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 4511101 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 4789099 THEN 'COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E MOTOCICLETAS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 4911600 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 5320202 THEN 'TRANSPORTE, ARMAZENAGEM E CORREIO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 5510801 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 5620104 THEN 'ALOJAMENTO E ALIMENTAÇÃO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 5811500 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 6399200 THEN 'INFORMAÇÃO E COMUNICAÇÃO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 6410700 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 6630400 THEN 'ATIVIDADES FINANCEIRAS, DE SEGUROS E SERVIÇOS RELACIONADOS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 6810201 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 6822600 THEN 'ATIVIDADES IMOBILIÁRIAS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 6911701 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 7500100 THEN 'ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E TÉCNICAS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 7711000 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 8299799 THEN 'ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEMENTARES'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 8411600 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 8430200 THEN 'ADMINISTRAÇÃO PÚBLICA, DEFESA E SEGURIDADE SOCIAL'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 8511200 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 8599699 THEN 'EDUCAÇÃO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 8610101 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 8800600 THEN 'SAÚDE HUMANA E SERVIÇOS SOCIAIS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 9001901 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 9329899 THEN 'ARTES, CULTURA, ESPORTE E RECREAÇÃO'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 9411100 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 9609299 THEN 'OUTRAS ATIVIDADES DE SERVIÇOS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 9700500 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 9700500 THEN 'SERVIÇOS DOMÉSTICOS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) >= 9900800 AND CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) <= 9900800 THEN 'ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS'
		WHEN CAST(ESTABELECIMENTOS.CNAE_PRINCIPAL AS INT) = 8888888  THEN 'NAO INFORMADO'
		ELSE 'NAO INFORMADO'
	END AS "CLASSE",
    ESTABELECIMENTOS.DDD1 || ESTABELECIMENTOS.TELEFONE1 AS "TELEFONE_1",
    ESTABELECIMENTOS.DDD2 || ESTABELECIMENTOS.TELEFONE2 AS "TELEFONE_2",
    ESTABELECIMENTOS.EMAIL AS "EMAIL",
	GEO.GEO AS "GEO",
	GEO.DISTRITO_PMF AS "DISTRITO",
	GEO.REGIONAL_ACIF AS "REGIONAL_ACIF",
	SOCIOS.NOME_SOCIO AS "NOME_SOCIO", 
	SOCIOS.CPF_CNPJ_SOCIO AS "CPF_SOCIO"

	FROM ESTABELECIMENTOS
		
	LEFT JOIN EMPRESAS
	ON ESTABELECIMENTOS.CNPJ_BASICO = EMPRESAS.CNPJ_BASICO

	LEFT JOIN SIMPLES
	ON ESTABELECIMENTOS.CNPJ_BASICO = SIMPLES.CNPJ_BASICO

	LEFT JOIN CNAE
	ON ESTABELECIMENTOS.CNAE_PRINCIPAL = CNAE.CODIGO_CNAE

	LEFT JOIN MUNICIPIO
	ON ESTABELECIMENTOS.MUNICIPIO = MUNICIPIO.CODIGO_MUNICIPIO

	LEFT JOIN GEO
	ON ESTABELECIMENTOS.CEP = GEO.CEP
	
	LEFT JOIN SOCIOS
	ON ESTABELECIMENTOS.CNPJ_BASICO = SOCIOS.CNPJ_BASICO

	WHERE ESTABELECIMENTOS.SITUACAO_CADASTRAL = '02' AND ESTABELECIMENTOS.MUNICIPIO = '8105'
	
	ORDER BY ESTABELECIMENTOS.CNPJ_BASICO || ESTABELECIMENTOS.CNPJ_ORDEM || ESTABELECIMENTOS.CNPJ_DV
;

--____________________________________________________________________________________



